
package com.smartcity.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "testServiceSoap", targetNamespace = "http://localhost/test")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TestServiceSoap {


    /**
     * 
     * @param address
     * @param emergencyLevel
     * @param service
     * @return
     *     returns boolean
     */
    @WebMethod(action = "http://localhost/test/handleRequest")
    @WebResult(name = "handleRequest", targetNamespace = "http://localhost/test")
    @RequestWrapper(localName = "handleRequest", targetNamespace = "http://localhost/test", className = "com.smartcity.soap.HandleRequest")
    @ResponseWrapper(localName = "handleRequestResponse", targetNamespace = "http://localhost/test", className = "com.smartcity.soap.HandleRequestResponse")
    public boolean handleRequest(
        @WebParam(name = "service", targetNamespace = "http://localhost/test")
        String service,
        @WebParam(name = "emergencyLevel", targetNamespace = "http://localhost/test")
        String emergencyLevel,
        @WebParam(name = "address", targetNamespace = "http://localhost/test")
        String address);

}
